=== mzazon/xml-parser/1transactions.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT UserId (#PCDATA)>
<!ELEMENT Transactions ((Transaction+))>
<!ELEMENT Transaction ((PaymentId, UserId, EventId, IsCompleted))>
<!ELEMENT EventId (#PCDATA)>
<!ELEMENT PaymentId (#PCDATA)>
<!ELEMENT IsCompleted (#PCDATA)>

=== mzazon/xml-parser/1tps_transaction_data.xml
<!DOCTYPE Transactions SYSTEM "1transactions.dtd">
<Transactions>
    <Transaction>
        <PaymentId>1</PaymentId>
        <UserId>1</UserId>
        <EventId>1</EventId>
        <IsCompleted>0</IsCompleted>
    </Transaction>
    <Transaction>
        <PaymentId>2</PaymentId>
        <UserId>2</UserId>
        <EventId>2</EventId>
        <IsCompleted>1</IsCompleted>
    </Transaction>
</Transactions>
