=== mzazon/xml-parser/payments.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"/>
	<xs:element name="Payments">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Payment" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="UserId" type="xs:string" />
							<xs:element name="Type" type="xs:string" />
							<xs:element name="Address" type="xs:string" />
							<xs:element name="City" type="xs:string" />
							<xs:element name="State" type="xs:string" />
							<xs:element name="Zip" type="xs:string" />
							<xs:element name="CardNumber" type="xs:string" />
							<xs:element name="FullName" type="xs:string" />
							<xs:element name="Expiration" type="xs:string" />
							<xs:element name="Cvv2" type="xs:string" />
							<xs:element name="PhoneNumber" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mzazon/xml-parser/tps_payment_data.xml
<Payments xsi:noNamespaceSchemaLocation="payments.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
<Payment>
  <UserId>2</UserId>
  <Type>Visa</Type>
  <Address>1971 Neil Ave</Address>
  <City>Columbus</City>
  <State>OH</State>
  <Zip>43210</Zip>
  <CardNumber>7364837445408241</CardNumber>
  <FullName>Mike Zazon</FullName>
  <Expiration>12-14</Expiration>
  <Cvv2>345</Cvv2>
  <PhoneNumber>6144418741</PhoneNumber>
</Payment>
</Payments>
