=== mzazon/xml-parser/venues.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"/>
	<xs:element name="Venues">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Venue" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string" />
							<xs:element name="Description" type="xs:string" />
							<xs:element name="Address" type="xs:string" />
							<xs:element name="City" type="xs:string" />
							<xs:element name="State" type="xs:string" />
							<xs:element name="Zip" type="xs:string" />
							<xs:element name="Size" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mzazon/xml-parser/tps_venue_data.xml
<Venues xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="venues.xsd">
	<Venue>
  		<Name>Jerome Schottenstein Center</Name>
  		<Description>The Value City Schottenstein Center is a multi purpose arena home to the OSU hockey, basketball, volleyball, and badmitton teams.</Description>
  		<Address>555 Borror Drive</Address>
  		<City>Columbus</City>
  		<State>OH</State>
  		<Zip>43201</Zip>
  		<Size>10</Size>
	</Venue>
	<Venue>
  		<Name>South Oval</Name>
  		<Description>The South Oval is an outdoor, open to public greenspace (grass) located just north of the south campus dorms.</Description>
  		<Address></Address>
  		<City></City>
  		<State></State>
  		<Zip></Zip>
  		<Size>6</Size>
	</Venue>
	<Venue>
  		<Name>OSU Stadium</Name>
  		<Description>Known as the SHOE!</Description>
  		<Address>411 Woody Hayes Drive</Address>
  		<City>Columbus</City>
  		<State>Ohio</State>
  		<Zip>43210</Zip>
  		<Size>8</Size>
	</Venue>
</Venues>
